### ISSUE TITLE
When combined with jh_opengraphprotocol, there are duplicate og:tags

### ISSUE THREAD

**Issue by ghost** [jonathanheilmann/ext-jh_opengraph_ttnews#6]
^ the problem is, og:tags of _ttnews are rendered _before_ og:tags of the other extension. _ttnews tags should be rendered last, because they are more specific. When a crawler finds duplicate tags, they will use the last tag. I can live with duplicate tags, but only if more specific tags come last.

**Comment by jonathanheilmann** [comment]
Which version of jh_opengraphprotocol do you use? Actual version 1.2.1 (https://typo3.org/extensions/repository/view/jh_opengraphprotocol) should solve this.

Actually, there is missing an dependency entry for jh_opengraph_ttnews...
